foodtracker/models.py
from sqlalchemy.orm import backref
from .extensions import db

log_food = db.Table('log_food',  
    db.Column('log_id', db.Integer, db.ForeignKey('log.log_id')),
    db.Column('food_id', db.Integer, db.ForeignKey('food.food_id'))
)

class Food(db.Model):
 
    food_id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(80), unique=True, nullable=False)
    proteins=db.Column(db.Integer, nullable=False)
    carbs=db.Column(db.Integer, nullable=False)
    fats=db.Column(db.Integer, nullable=False)

    @property
    def calories(self):
        return self.proteins * 4 + self.carbs * 4 + self.fats * 9

class Log(db.Model):
    log_id=db.Column(db.Integer, primary_key=True)
    date=db.Column(db.Date, nullable=True)
    foods=db.relationship('Food', secondary=log_food, backref=db.backref('logs', lazy='dynamic'))

foodtracker/__init__.py
from flask import Flask
from logging import debug
from .main.routes import main
from .extensions import db
from .models import Food


def create_app():
    app=Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI']= 'mysql://root:@localhost/foodtracker'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']= False


    db.init_app(app)

    app.register_blueprint(main)

    return app    

 

foodtracker/main/routes.py
import datetime
from logging import log
from flask import Blueprint, render_template, session
from flask.globals import request
from flask.helpers import url_for
from werkzeug.utils import redirect
from foodtracker.models import Food, Log
from foodtracker.extensions import db
from datetime import datetime

main=Blueprint('main', __name__)

@main.route('/')
def index():
    logs=Log.query.order_by(Log.date.desc()).all()

    log_dates=[]
    
    for log in logs:
        proteins=0
        carbs=0
        fats=0
        calories=0
        
        for food in log.foods:
            proteins += food.proteins
            carbs += food.carbs
            fats += food.fats
            calories += food.calories

        log_dates.append({
            'log_date':log,
            'proteins' : proteins,
            'carbs': carbs,
            'fats': fats,
            'calories' : calories
        })    
    return render_template('index.html', log_dates=log_dates)

@main.route('/create_log', methods=['POST'])
def create_log():
    date = request.form.get('date')
    log = Log(date=datetime.strptime(date, '%Y-%m-%d'))
    db.session.add(log)
    db.session.commit()
    return redirect(url_for('main.view', log_id=log.log_id))

@main.route('/add')
def add():
    foods=Food.query.all()
    return render_template('add.html', foods=foods, food=None)

@main.route('/add', methods=['GET','POST'])    
def add_post():
    foodname=request.form.get('food-name')
    proteins=request.form.get('protein')
    carbs=request.form.get('carbohydrates')
    fats=request.form.get('fat')
    
    food_id=request.form.get('food-id')

    if food_id:
        food=Food.query.get(food_id)
        food.name=foodname
        food.proteins=proteins
        food.carbs=carbs
        food.fats=fats
    else:
        new_food=Food(name=foodname, proteins=proteins, carbs=carbs, fats=fats)
        db.session.add(new_food)
    db.session.commit()
    return redirect(url_for('main.add'))

@main.route('/delete_food/<int:food_id>')
def delete_food(food_id):
    food=Food.query.get(food_id)
    db.session.delete(food)
    db.session.commit()
    return redirect(url_for('main.add'))    

@main.route('/edit_food/<int:food_id>')
def edit_food(food_id):
    food=Food.query.get(food_id)
    foods=Food.query.all()
    
    return render_template('add.html', food=food, foods=foods, log=log)


@main.route('/view/<int:log_id>')
def view(log_id):
    log=Log.query.get_or_404(log_id)
    foods=Food.query.all()

    totals={
        'protein':0,
        'carbs':0,
        'fat':0,
        'calories':0
    }
    for food in log.foods:
        totals['protein'] += food.proteins
        totals['carbs'] += food.carbs
        totals['fat'] += food.fats
        totals['calories'] += food.calories
    return render_template('view.html', foods=foods, log=log, totals=totals)

@main.route('/add_food_to_log/<int:log_id>', methods=['POST'])
def add_food_to_log(log_id):
    log=Log.query.get(log_id)
    
    selected_food=request.form.get('food-select')
    food=Food.query.get(int(selected_food))
    log.foods.append(food)
    db.session.commit()
    return redirect(url_for('main.view', log_id=log_id))    

@main.route('/remove_food_from_log/<int:log_id>/<int:food_id>')
def remove_food_from_log(log_id, food_id):
    log = Log.query.get(log_id)
    food = Food.query.get(food_id)

    log.foods.remove(food)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log_id))

foodtracker/templates/add.html
{% extends "layout.html" %}
{% block title %} Food Tracker | Add Food Item {% endblock %}
{% block body %}
<style>
    .nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus{
    color: #fff;
    border-bottom: 3px solid rgba(0, 0, 0, 0.1);
    font-weight: bolder;
    background:rgba(0, 0, 0, 0.4);
    width: 150px;
    margin-left: 270px;
    
}
.nav>li.active>a:hover, .nav>li.active>a:focus{
    background: rgba(23, 23, 24, 0.4);
}

.nav-pills>li.addfood>a, .nav-pills>li.addfood>a:hover, .nav-pills>li.addfood>a:focus{
    color: #fff;
    border-bottom: 3px solid #2fa4e7;
    font-weight: bolder;
    background:rgba(0, 0, 0, 0.4);
    width: 150px;
    margin-right: 90px;
}
.panel{
    width: 510px;
    margin-left: 270px;
}
.panel-body{
    width: 450px;
    margin-left: 30px;
    margin-bottom: 0px;
}
.panel-2{
    width: 950px;
    margin-left: 50px;
    
}

body{
    background: rgba(0, 0, 0, 0.4);
    font-family: 'Ubuntu', sans-sarif;
}
#homeJumbo{
      position: relative;
      min-height: 180;
      background: rgba(44, 62, 80, .8);
      background-image: url(" {{ url_for('static', filename='img/bg.jpg')}} ");
      background-size: cover;
      background-repeat: no-repeat;
      border-bottom: 2px solid rgba(44, 62, 80, .8);
      box-shadow: 7px 1px 2px 2px rgba(44, 62, 80, .8);
      margin-bottom: 15px;
      
}
#homeJumbo > div.overlay{
    position: absolute;
    height: 183px;
    width: 100%;
    background: rgba(44, 62, 80, .6);
}
#homeJumbo h1{
    font-size: 30px;
    color: #fff;
    font-family: 'Oswald';
    text-align: center;
    padding-top: 20px;
    font-weight: bolder;
}
#homeJumbo h1 > a{
    color: #fff;
    text-decoration: none;
}


</style>
<div class="container-fluid" id="wrapper">
        <div class="row" id="homeJumbo" style="background-image: url(' {{ url_for('static', filename='img/bg.jpg')}} ');">
            <div class="overlay"></div>
            <div class="col-lg-12">
                <h1>
                    <a href="{{url_for('main.index')}}">FOOD TRACKER</a>
                </h1>
                <div class="row t20">
                    <div class="col-lg-4 col-lg-offset-4">
                        <ul class="nav nav-pills nav-justified">
                           <li role="presentation" class="active">
                               <a href="{{url_for('main.index')}}" title="Home"><i class="fas fa-home" style=" margin-right: 10px;"></i>Home</a>
                           </li>
                           <li role="presentation" class="addfood">
                                <a href="{{url_for('main.add')}}" title="Add Food Item">Add Food Item</a>
                           </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="row t20">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-default" id="foodform">
                    <div class="panel-body">
                        <h3 class="lean-h text-black">
                            <i class="fas fa-plus-circle"></i>New Food Form
                        </h3>
                        <hr/>
                        <form action="{{url_for('main.add')}}" class="row" method="POST" role="form">
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="food-name">Food Name</label>
                                        <input type="text" class="form-control" name="food-name" id="food-name" placeholder="Food Name" value="{{food.name}}" autofocus>
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="protein">Protein</label>
                                        <input type="number" class="form-control" name="protein" id="protein" placeholder="Protein" value="{{food.proteins}}">
                                    </div>
                                </div>

                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="carbohydrates">Carbohydrates</label>
                                        <input type="number" class="form-control" name="carbohydrates" id="carbohydrates" placeholder="Carbohydrate" value="{{food.carbs}}">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label for="fat">Fat</label>
                                        <input type="number" name="fat" id="fat" placeholder="Fat" value="{{food.fats}}">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="form-group">
                                        <label style="visibility: hidden;">Submit</label>
                                        <input type="hidden" name="food-id" value="{{food.food_id}}">
                                        <button type="submit" class="btn btn-primary btn-block">
                                            <i class="fas fa-cloud-upload-alt" style="margin-right: 5px;"></i>Submit
                                        </button>
                                    </div>
                                </div>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
       
        <div class="row t20">
            <div class="col-lg-4 col-lg-offset-2">
                <div class="panel panel-default panel-2" id="foodform">
                    <div class="panel-body">
                        <h4>
                            <i class="fas fa-th-list" style="margin-right: 5px;"></i>Existing Food Item
                        </h4>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th style="width: 5%;">#</th>
                                    <th>Name</th>
                                    <th style="width: 10%;">Protein</th>
                                    <th style="width: 16%;">Carbohydrates</th>
                                    <th style="width: 10%;">Fat</th>
                                    <th style="width: 12%;">Calories</th>
                                    <th style="width: 20%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for food in foods  %}
                                <tr>
                                    <td>{{food.food_id}}</td>
                                    <td>{{food.name}}</td>
                                    <td>{{food.proteins}}</td>
                                    <td>{{food.carbs}}</td>
                                    <td>{{food.fats}}</td>
                                    <td>{{food.calories}}</td>
                                    <td>
                                        <a href="{{url_for('main.edit_food', food_id=food.food_id)}}" class="btn btn-default btn-xs"><i class="fas fa-edit" style="margin-right: 3px;"></i>Edit</a>
                                        <a href="{{url_for('main.delete_food', food_id=food.food_id)}}" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt" style="margin-right: 3px;"></i> Del</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
       
{% endblock %}        

foodtracker/templates/index.html
{% extends "layout.html" %}
{% block title %} Food Tracker | Home {% endblock %}
{% block body %}
<style>
    .panel-default{
    width: 450px;
    margin-left: 300px;
}
.panel-warning{
    width: 300px;
    display: inline-block;
    margin-left: 32px;
}

</style>

    <div class="container-fluid" id="wrapper">
        <div class="row" id="homeJumbo" style="background-image: url(' {{ url_for('static', filename='img/bg.jpg')}} ');">
            <div class="overlay"></div>
            <div class="col-lg-12">
                <h1>
                    <a href="{{url_for('main.index')}}">FOOD TRACKER</a>
                </h1>
                <div class="row t20">
                    <div class="col-lg-4 col-lg-offset-4">
                        <ul class="nav nav-pills nav-justified">
                           <li role="presentation" class="active">
                               <a href="{{url_for('main.index')}}" title="Home"><i class="fas fa-home" style=" margin-right: 10px;"></i>Home</a>
                           </li>
                           <li role="presentation">
                                <a href="{{url_for('main.add')}}" title="Add Food Item">Add Food Item</a>
                           </li>
                        </ul>
                    </div>

                </div>

            </div>

        </div>

    <div class="row t20">
     <div class="col-lg-4 col-lg-offset-4">
         <div class="panel panel-default">
            <div class="panel-body">
                <form action="{{url_for('main.create_log')}}" role="form" method="POST">
                    <div class="form-group">
                        <label for=""><i class="fas fa-plus-circle" style="margin-right: 3px;"></i>Add New Date</label>
                        <div class="input-group">
                            <input type="date" class="form-control" name="date" placeholder="Select New Date" aria-describedby="add-btn">
                            <span class="input-group-btn">
                                <button type="submit" id="add-btn" class="btn btn-primary">
                                    <i class="fas fa-plus-circle"></i> Add Date
                                </button>
                            </span>
                        </div>

                    </div>
                </form>
            </div>
            
         </div>
     </div>
    </div>
    
    <div class="row t20">
        <div class="col-lg-12">
            <h4 class="text-center text-white"><strong>Esisting Record ({{ log_dates|length }})</strong></h4>
        </div>
    </div>
    {% for row in log_dates|batch(3) %}
    <div class="row t20">
        <div class="col-lg-3">
            {% for log_date in row %}
            <div class="panel panel-warning">
                <div class="panel-body text-bold">
                    <i class="fas fa-calendar-alt"></i>{{log_date['log_date'].date.strftime('%B %d, %Y')}}
                    <a href="{{url_for('main.view', log_id=log_date['log_date'].log_id)}}" class="btn btn-primary btn-xs pull-right">View
                        <i class="fas fa-arrow-circle-right"></i>
                    </a>
                </div>
                <ul class="list-group">
                    <li class="list-group-item text-bold"><span class="badge">{{log_date['proteins']}}</span>Protein</li>
                    <li class="list-group-item text-bold"><span class="badge">{{log_date['carbs']}}</span> Carbohydrate</li>
                    <li class="list-group-item text-bold"><span class="badge">{{log_date['fats']}}</span>Fat</li>
                    <li class="list-group-item text-bold"><span class="badge">{{log_date['calories']}}</span>Calories</li>
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    
{% endblock %}    

foodtracker/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>{%  block title %} {% endblock %}</title>
    
    <!-- google fonts link -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">
    <!-- Bootstrap css -->
    <link rel="stylesheet" href="{{url_for('static', filename='bs/css/united.min.css')}}">
    <!-- custom css -->
    <link rel="stylesheet" href="static/styles.css">
      
    <!-- google fonts -->
    
  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'  rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>
  {% block body %}
  {% endblock %}


    <footer>
        <div class="row pad">
            <div class="col-lg-12 text-center">
                Copyright &copy;  2021 <strong>Food Tracker</strong>
            </div>
        </div>
    </footer>
</div>

<!-- jquery js -->
<script src="{{url_for('static', filename='bs/js/jquery.min.js')}}"></script>
<!-- bootstrap js -->
<script src="{{url_for('static', filename='bs/js/bootstrap.min.js')}}"></script>
</body>
</html>

foodtracker/templates/view.html
{% extends "layout.html" %}
{% block title %} Food Tracker | View Details {% endblock %}
{% block body %}

<style>
    
    body{
    background: rgba(0, 0, 0, 0.4);
    font-family: 'Ubuntu', sans-sarif;
}
#homeJumbo{
      position: relative;
      min-height: 180;
      background: rgba(44, 62, 80, .8);
      background-image: url(" {{ url_for('static', filename='img/bg.jpg')}} ");
      background-size: cover;
      background-repeat: no-repeat;
      border-bottom: 2px solid rgba(44, 62, 80, .8);
      box-shadow: 7px 1px 2px 2px rgba(44, 62, 80, .8);
      
}
#homeJumbo > div.overlay{
    position: absolute;
    height: 183px;
    width: 100%;
    background: rgba(44, 62, 80, .6);
}
#homeJumbo h1{
    font-size: 30px;
    color: #fff;
    font-family: 'Oswald';
    text-align: center;
    padding-top: 20px;
    font-weight: bolder;
    margin-left: 80px;
}
#homeJumbo h1 > a{
    color: #fff;
    text-decoration: none;
}
.t10{
    margin-top: 10px;
}
.t20{
    margin-top: 20px;
}
.f25{
    font-size: 25px;
}
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus{
    color: #fff;
    border-bottom: 3px solid  rgba(0, 0, 0, 0.1);
    font-weight: bolder;
    background:rgba(0, 0, 0, 0.4);

    

}
.nav-pills>li.view>a, .nav-pills>li.view>a:hover, .nav-pills>li.view>a:focus{
    color: #fff;
    border-bottom: 3px solid #2fa4e7;
    font-weight: bolder;
    background:rgba(0, 0, 0, 0.4);
    margin-right: 10px ;

}
.nav-pills>li.addfood>a, .nav-pills>li.addfood>a:hover, .nav-pills>li.addfood>a:focus{
    color: #fff;
    border-bottom: 3px solid rgba(0, 0, 0, 0.1);
    font-weight: bolder;
    background:rgba(0, 0, 0, 0.4);
    width: 150px;
    
}
.nav-justified>li>a{
    color: #fff;
    font-weight: bolder;
}
.nav>li>a:hover, .nav>li>a:focus{
    background: rgba(0, 0, 0, 0.4);
}
.nav-pills>li+li{
    padding-left: 10px;
}
.nav-pills>li.active>a{
    width: 150px;
    margin-left: 230px;
}
.nav-pills>li>a{
    width: 150px;
}


.text-bold{
    font-weight: bolder !important;
}
.lean-h{
    margin-top: 5px;
    margin-bottom: 10px;
    font-weight: bolder;
}
.text-black{
    color: #000 !important;
}
.text-white{
    color: #fff !important;
}
footer{
    margin-top: 20px;
    color: #000;
    margin-bottom: 20px;
}
.panel-default{
    width: 450px;
    margin-left: 300px;
}
.panel-3{
    width: 790px;
    margin-left: 120px;
}


</style>

<div class="container-fluid" id="wrapper">
        <div class="row" id="homeJumbo" style="background-image: url(' {{ url_for('static', filename='img/bg.jpg')}} ');">
            <div class="overlay"></div>
            <div class="col-lg-12">
                <h1>
                    <a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
                </h1>
                
                <div class="row t20">
                    <div class="col-lg-4 col-lg-offset-4">
                        <ul class="nav nav-pills nav-justified">
                          <li role="presentation" class="active">
                              <a href="{{ url_for('main.index') }}" title="Home">Home</a>
                          </li>
                          <li role="presentation" class="addfood">
                              <a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
                          </li>
                          <li role="presentation" class="view">
                            <a href="{{ url_for('main.index') }}" title="Home">View Details</a>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="row t20">
            <div class="col-lg-4 col-lg-offset-4">
               <div class="panel panel-default">
                   <div class="panel-body">
                       <form action="{{url_for('main.add_food_to_log', log_id=log.log_id)}}" method="POST" role="form">
                           <div class="form-group">
                               <label for="">Add Food</label>
                               <div class="input-group">
                                   <select name="food-select" class="form-control">
                                       {% for food in foods %}
                                       <option value="{{food.food_id}}">{{food.name}}</option>
                                       {% endfor %}
                                   </select>
                                   <span class="input-group-btn">
                                      <button class="btn btn-primary" id="add-btn">
                                        <i class="fas fa-plus-circle"></i> Add Food
                                      </button>
                                   </span>
                               </div>
                           </div>
                       </form>
                   </div>
               </div>
            </div>
        </div>
       <div class="row t20">
           <div class="col-lg-8 col-lg-offset-2">
             <div class="panel panel-default panel-3" style="width: 750p;">
                <div class="panel-body">
                    <h3 class="lean-h text-black">
                        <i class="fas fa-calendar-alt"></i> {{log.date.strftime('%B %d, %Y')}}
                    </h3>
                    <div class="row">
                        <div class="col-md-3">
                            <h4 class="lean-h">
                                Protein: &nbsp; <strong class="f15">{{totals['protein']}}</strong>
                            </h4>
                        </div>
                        
                        <div class="col-md-3">
                            <h4 class="lean-h">
                                Carbohydrate: &nbsp; <strong class="f15">{{totals['carbs']}}</strong>
                            </h4>
                        </div>    
                        <div class="col-md-3">
                            <h4 class="lean-h">
                                Fat: &nbsp; <strong class="f15">{{totals['fat']}}</strong>
                            </h4>
                        </div>
                        
                        <div class="col-md-3">
                            <h4 class="lean-h">
                                Calories: &nbsp; <strong class="f15">{{totals['calories']}}</strong>
                            </h4>
                        </div>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-hover table-striped table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 5%;">#</th>
                                <th>Name</th>
                                <th style="width: 10%;">Protein</th>
                                <th style="width: 16%;">Carbohydrates</th>
                                <th style="width: 10%;">Fat</th>
                                <th style="width: 12%;">Calories</th>
                                <th style="width: 20%;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for food in log.foods %}
                            <tr>
                                <td>{{loop.index}}</td>
                                <td>{{food.name}}</td>
                                <td>{{food.proteins}}</td>
                                <td>{{food.carbs}}</td>
                                <td>{{food.fats}}</td>
                                <td>{{food.calories}}</td>
                                <td>
                                    <a href="{{ url_for('main.remove_food_from_log', log_id=log.log_id, food_id=food.food_id) }}" class="btn btn-danger btn-xs"><i class="fas fa-trash-alt" style="margin-right: 3px;"></i> Del</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
             </div>
           </div>
       </div>

{% endblock %}      